version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/tajmahal-healthcare
      - SESSION_SECRET=tajmahalhealthcare_development
      - NODE_ENV=development
    volumes:
      - ./public/uploads:/usr/src/app/public/uploads
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: 